spring:
  datasource:
    username: root
    password: cjc89684550
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mmal?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC

  profiles:
    active: dev

  thymeleaf:
    cache: false
#配置日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  #逻辑删除
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

server:
  port: 8110